# Generated by Django 5.0.14 on 2026-06-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentqueryaudit',
            new_name='agent_query_user_id_1d87da_idx',
            old_name='agent_query_audit_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='agentqueryaudit',
            new_name='agent_query_success_977635_idx',
            old_name='agent_query_audit_success_created_idx',
        ),
        migrations.RenameIndex(
            model_name='agentqueryaudit',
            new_name='agent_query_created_ec03ee_idx',
            old_name='agent_query_audit_created_idx',
        ),
    ]
