# Generated by Django 5.0.14 on 2025-08-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesauthuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesauthuser',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
