# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0002_alter_salesauthuser_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesauthuser",
            name="identity_provider",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("microsoft", "Microsoft Entra ID"),
                    ("legacy_ad", "Legacy Active Directory"),
                ],
                default="local",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="salesauthuser",
            name="azure_ad_tenant_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="salesauthuser",
            name="azure_ad_object_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="salesauthuser",
            name="last_microsoft_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="salesauthuser",
            index=models.Index(
                fields=["azure_ad_tenant_id", "azure_ad_object_id"],
                name="sales_auth_ms_tid_oid_idx",
            ),
        ),
    ]
