# Generated by Django 5.0.14 on 2025-08-18 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=255)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'Depo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=255)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'Territory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=255)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'Zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTerritoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('territory', models.ForeignKey(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='user_auth.territory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='territory_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserTerritoryMap',
            },
        ),
        migrations.CreateModel(
            name='UserZoneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='zone_links', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='user_auth.zone')),
            ],
            options={
                'db_table': 'UserZoneMap',
            },
        ),
        migrations.CreateModel(
            name='UserDepoMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depo', models.ForeignKey(db_column='depo_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='user_auth.depo')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='depo_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserDepoMap',
                'indexes': [models.Index(fields=['user'], name='ix_udm_user'), models.Index(fields=['depo'], name='ix_udm_depo')],
            },
        ),
        migrations.AddConstraint(
            model_name='userdepomap',
            constraint=models.UniqueConstraint(fields=('user', 'depo'), name='uq_user_depo'),
        ),
        migrations.AddIndex(
            model_name='userterritorymap',
            index=models.Index(fields=['user'], name='ix_utm_user'),
        ),
        migrations.AddIndex(
            model_name='userterritorymap',
            index=models.Index(fields=['territory'], name='ix_utm_territory'),
        ),
        migrations.AddConstraint(
            model_name='userterritorymap',
            constraint=models.UniqueConstraint(fields=('user', 'territory'), name='uq_user_territory'),
        ),
        migrations.AddIndex(
            model_name='userzonemap',
            index=models.Index(fields=['user'], name='ix_uzm_user'),
        ),
        migrations.AddIndex(
            model_name='userzonemap',
            index=models.Index(fields=['zone'], name='ix_uzm_zone'),
        ),
        migrations.AddConstraint(
            model_name='userzonemap',
            constraint=models.UniqueConstraint(fields=('user', 'zone'), name='uq_user_zone'),
        ),
    ]
