# Generated by Django 5.0.14 on 2026-03-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_depo_territory_zone_userterritorymap_userzonemap_and_more'),
        ('user_auth', '0002_otptoken'),
    ]

    operations = [
    ]
