# Generated by Django 5.0.14 on 2025-06-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
