# Generated by Django 5.0.14 on 2026-01-28 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='MessageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=16)),
                ('meta_json', models.JSONField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.message')),
            ],
            options={
                'db_table': 'message_meta',
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='message_met_convers_3faa60_idx')],
            },
        ),
    ]
