# Generated by Django 5.0.14 on 2026-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kql',
            field=models.TextField(blank=True, null=True),
        ),
    ]
